config/routes.rb
Rails.application.routes.draw do
  get 'sign-up' => 'users#new'
  get 'settings' => 'users#show'
  resources :users, :only => [:create, :update]

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions, :only => [:create]
  resources :dashboard, :only => [:index]
  resources :checks, :only => [:edit, :update]
  resources :hooks, :only => [:edit, :update]

  resources :tests, :only => [:index, :new, :create, :show, :edit, :update] do
    resources :checks, :only => [:new, :create]
    resources :hooks, :only => [:new, :create]
    resources :test_runs, :only => [:create]
  end

end

app/views/shared/list/_test.html.erb
<li id="test-<%= test.id %>" class="test-item list-group-item">
  <div>
    <div class="test-top">
      <span class="glyphicon glyphicon-<%= test.last_success ? 'ok text-success' : 'remove text-danger' %>"></span>
      <span class="test-title"><%= link_to (test.name || "#{test.style.titleize} Test #{test.index}"), test_path(test) %></span>
      <!-- RHS -->

      <div class="pull-right test-edit dropdown list-inline">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More</a>
        <ul class="dropdown-menu">
          <li><a href="<%= edit_test_path(test) %>">Edit</a></li>
          <li><a href="<%= new_test_check_path(test) %>">Add a Check</a></li>
          <li>
            <a>
              <form action="<%= test_test_runs_path(test) %>" method="post">
                <%= csrf_form_tags %>
                <button class="btn btn-link" role="link" name="run_now">Run Now</button>
              </form>
            </a>
          </li>
        </ul>
      </div>
      <span class="pull-right test-ago"><%= test.last_at && "#{time_ago_in_words(test.last_at)} ago" %></span>
      <span class="pull-right test-time"><%= test.last_duration.to_i %>ms</span>
      <span class="pull-right test-code label label-<%= test.last_success ? 'success' : 'danger' %>">Status <%= test.last_code %></span>
    </div>
    <div>
      <!-- LHS -->
      <span class="test-breed"><%= test.breed.upcase %></span>
      <span class="test-url"><%= test.url %></span>
      <span class="test-every">every&nbsp;<%= distance_of_time_in_words(test.interval).gsub('about ', '') %></span>
    </div>
  </div>
  <div class="test-info">
    <% if test.headers %>
      <div>
        <a class="btn test-toggle test-headers-toggle" data-toggle="collapse" data-target="#test-<%= test.id %> .test-headers">Headers <span class="caret"></span></a>
        <div class="test-headers collapse">
          <code>
            <% JSON.parse(test.headers).map {|(k,v)| "#{k}: #{v}" }.each do |header| %>
              <%= header %>
              <br>
            <% end %>
          </code>
        </div>
      </div>
    <% end %>
    <% if test.body %>
      <div>
        <a class="btn test-toggle test-body-toggle" data-toggle="collapse" data-target="#test-<%= test.id %> .test-body">Body <span class="caret"></span></a>
        <div class="test-body collapse"><code><%= test.body %></code></div>
      </div>
    <% end %>
  </div>

  <div class="test-checks-list">
    <% checks = test.checks.to_a %>
    <a class="btn test-toggle test-checks-toggle" data-toggle="collapse" data-target="#test-<%= test.id %> .test-checks">Checks (<%= checks.size %>) <span class="caret"></span></a>
    <a class="btn test-toggle test-checks-new" href="<%= new_test_check_path(test) %>"><span class="glyphicon glyphicon-plus"></span><span>Add a Check</span></a>

    <div class="test-checks collapse in">
      <ul class="test-check-items list-group">
        <% checks.each do |check| %>
          <li id="check-<%= check.id %>" class="list-group-item">
            <span><%= check.decorator.new(check) %></span>
            <span class="pull-right check-edit"><a href="<%= edit_check_path(check) %>">Edit</a></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="test-hooks-list">
    <% hooks = test.hooks.to_a %>
    <a class="btn test-toggle test-hooks-toggle" data-toggle="collapse" data-target="#test-<%= test.id %> .test-hooks">WebHooks (<%= hooks.size %>) <span class="caret"></span></a>
    <a class="btn test-toggle test-hooks-new" href="<%= new_test_hook_path(test) %>"><span class="glyphicon glyphicon-plus"></span><span>Add a WebHook</span></a>

    <div class="test-hooks collapse">
      <ul class="test-hook-items list-group">
        <% hooks.each do |hook| %>
          <li id="hook-<%= hook.id %>" class="list-group-item">
            <span><%= hook.name %></span>
            <span class="label label-<%= hook.enabled ? 'success' : 'danger' %>"><%= hook.enabled ? 'Enabled' : 'Disabled' %></span>
            <span class="pull-right hook-edit"><a href="<%= edit_hook_path(hook) %>">Edit</a></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>


</li>

app/views/shared/list/_test_run.html.erb
<li id="test_run-<%= test_run.id %>" class="list-group-item test_run-item">
  <div>
    <div class="test-top">
      <% if test_run.code > 0 %>
      <span class="glyphicon glyphicon-<%= test_run.failed_check_id ? 'remove text-danger' : 'ok text-success' %>"></span>
      <span class="test-status"><%= test_run.failed_check_id ? 'Failed' : 'Passed' %></span>
      <span class="test-at"><%= test_run.at && "#{time_ago_in_words(test_run.at)} ago" %></span>
      <% else %>
      <span class="test-status">Pending</span>
      <% end %>

      <!-- RHS -->
      <span class="pull-right test-time"><%= test_run.duration.zero? ? '' : "#{test_run.duration.to_i}ms"  %></span>
      <span class="pull-right test-code label label-<%= test_run.failed_check_id ? 'danger' : 'success' %>">Status <%= test_run.code > 0 ? test_run.code : '-' %></span>
    </div>
  </div>
  <div class="test-failed_check">
  <% if test_run.failed_check_id %>
    <ul class="test-check-items list-group">
      <li id="check-<%= test_run.failed_check.id %>" class="list-group-item">
        <span>Failing check: <%= test_run.failed_check.decorator.new(test_run.failed_check) %></span>
        <span class="pull-right check-edit"><a href="<%= edit_check_path(test_run.failed_check) %>">Edit</a></span>
      </li>
    </ul>
  <% end %>
  </div>
  <div class="test-info">
    <% if test_run.headers.present? %>
      <div>
        <a class="btn test-toggle test-headers-toggle" data-toggle="collapse" data-target="#test_run-<%= test_run.id %> .test-headers">Headers <span class="caret"></span></a>
        <div class="test-headers collapse">
          <code>
          <% JSON.parse(test_run.headers).map {|(k,v)| "#{k}: #{v}" }.each do |header| %>
            <%= header %>
            <br>
          <% end %>
          </code>
        </div>
      </div>
    <% end %>
    <% if test_run.body.present? %>
      <div>
        <a class="btn test-toggle test-body-toggle" data-toggle="collapse" data-target="#test_run-<%= test_run.id %> .test-body">Body <span class="caret"></span></a>
        <div class="test-body collapse"><code><%= test_run.body %></code></div>
      </div>
    <% end %>
  </div>
</li>