config/routes.rb
Rails.application.routes.draw do
  get 'sign-up' => 'users#new'
  get 'settings' => 'users#show'
  resources :users, :only => [:create, :update]

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions, :only => [:create]
  resources :dashboard, :only => [:index]
  resources :checks, :only => [:edit, :update]
  resources :hooks, :only => [:edit, :update]

  resources :tests, :only => [:index, :new, :create, :show, :edit, :update] do
    resources :checks, :only => [:new, :create]
    resources :hooks, :only => [:new, :create]
    resources :test_runs, :only => [:create]
  end

end

app/models/user.rb
class User < Model
  attrs String => { :email => :e, :password => :p, :salt => :s, :token => :t },
    Integer => { :test_index => :ti },
    Mongoid::Boolean => { :notify_email => :ne, :notify_slack => :ns }

  allow :notify_email, :notify_slack

  validates :email, :password, :presence => true

  has_many :tests, :test_runs

  def password_is?(string)
    password == Digest::SHA256.hexdigest("#{string}|#{salt}")
  end

  def password=(string)
    self[:salt] = Base62.token
    self[:password] = string.presence && Digest::SHA256.hexdigest("#{string}|#{salt}")
  end

  private

  def defaults_before_create
    self.token = Base62.token
    self.notify_email = true
  end

end

app/controllers/users.rb
class Users < Application
  skip_before_action :authenticate!, :only => [:new, :create]

  html :new, :show

  def create
    user = User.new(params.permit(:email, :password))
    success = user.save && set_cookie(:id, user.id) && set_cookie(:token, user.token)

    redirect_to(success ? dashboard_index_path : sign_up_path)
  end

  def update
    params[:notify_email] = params[:notify_email] == 'on'
    params[:notify_slack] = params[:notify_slack] == 'on'

    user.update(params.permit(*User.allows))

    redirect_to settings_path
  end

end

app/views/users/new.html.erb
<div class="container">
  <form class="form-signin" method="post" action="<%= users_path %>">
    <h2 class="form-signin-heading">Please sign up</h2>
    <label for="email" class="sr-only">Email address</label>
    <input type="email" id="email" class="form-control" name="email" placeholder="Email address" required="" autofocus="">
    <label for="password" class="sr-only">Password</label>
    <input type="password" id="password" class="form-control" name="password" placeholder="Password" required="">
    <%= csrf_form_tags %>
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign Up</button>
  </form>
</div>

app/views/users/show.html.erb
<%= render :partial => 'shared/top' %>

<div class="col-md-3"></div>
<div class="panel panel-default col-md-6">
  <fieldset>
    <legend>Information</legend>
  </fieldset>

  <div class="form-group">
    <div>API Key: <span><code><%= user.token %></code></span></div>
    <div class="text-muted"><small>Your Key is used to make API calls from the client libraries to Alive.</small></div>
  </div>

  <form class="form-horizontal" method="post" action="<%= user_path(user) %>">
    <fieldset>
      <legend>Notifications</legend>

      <% via = [('slack' if user.notify_slack), ('email' if user.notify_email)].compact %>
      <% if via.any? %>
      <div>Notifying via <%= via.to_sentence %> on change in status.</div>
      <% else %>
      <div>You will not be notified of failing tests.</div>
      <% end %>

      <div class="form-group">
        <label class="col-md-3 control-label" for="notify_email">Notify by Email</label>
        <div class="col-md-9">
          <input id="notify_email" name="notify_email" type="checkbox" <%= 'checked ' if user.notify_email %>class="form-control input-md">
        </div>
      </div>

      <div class="form-group">
        <label class="col-md-3 control-label" for="notify_slack">Notify by Slack</label>
        <div class="col-md-9">
          <input id="notify_slack" name="notify_slack" type="checkbox" <%= 'checked ' if user.notify_slack %>class="form-control input-md">
        </div>
      </div>

      <input type="hidden" name="_method" value="patch">
      <%= csrf_form_tags %>

      <div class="form-group pull-right">
        <label class="control-label" for="update"></label>
        <div class="col-md-1">
          <button id="update" name="update" class="btn btn-primary">Update</button>
        </div>
      </div>
    </fieldset>
  </form>
</div>