config/routes.rb
Rails.application.routes.draw do
  get 'sign-up' => 'users#new'
  get 'settings' => 'users#show'
  resources :users, :only => [:create, :update]

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resources :sessions, :only => [:create]
  resources :dashboard, :only => [:index]
  resources :checks, :only => [:edit, :update]
  resources :hooks, :only => [:edit, :update]

  resources :tests, :only => [:index, :new, :create, :show, :edit, :update] do
    resources :checks, :only => [:new, :create]
    resources :hooks, :only => [:new, :create]
    resources :test_runs, :only => [:create]
  end

end

app/views/shared/_top.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Alive?', dashboard_index_path, :class => 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', dashboard_index_path %></li>
        <li><%= link_to 'Tests', tests_path %></li>
        <li><%= link_to 'Settings', settings_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Tests', tests_path %></li>
            <li><%= link_to 'Create a Test', new_test_path %></li>
            <li role="separator" class="divider"></li>
            <li class="dropdown-header">Settings</li>
            <li><%= link_to 'Notification settings', settings_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Log out', logout_path %></li>
      </ul>
    </div>
  </div>
</nav>

<div class="navbar-spacer"></div>